### ISSUE TITLE
Source distribution missing on PyPi for 0.9 release

### ISSUE THREAD

**Issue by gs-kamnas** [wasilak/yamllint-junit#10]
Hello @wasilak,

I have noticed that the source distribution appears to be missing on PyPi for the latest (0.9) release of this project. By any chance would you be able to upload a source as well as binary/wheel distribution to PyPi?

Specifically, I'm referring to the contents of this location on PyPi: https://pypi.org/project/yamllint-junit/0.9/#files

**Comment by wasilak** [comment]
Hey @gs-kamnas , thanks for noticing :) I've fixed it in version `0.10.1` (check it out) as well as I've merged your PR. Sorry for delay!
